name: flutterfire_workspace

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  cli_util: ^0.4.1
  glob: ^2.1.2
  intl: ^0.19.0
  melos: ^5.3.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  yaml: ^3.1.2
  
