blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/firebase/flutterfire/discussions/new?category=q-a
    about: Ask the community for help.
  - name: Show and tell
    url: https://github.com/firebase/flutterfire/discussions/new?category=show-and-tell
    about: Share what you've built with FlutterFire.
