name: firebase_remote_config_web
description: The web implementation of firebase_remote_config
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_remote_config/firebase_remote_config_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_remote_config/firebase_remote_config_web

version: 1.6.12

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core: ^3.3.0
  firebase_core_web: ^2.17.4
  firebase_remote_config_platform_interface: ^1.4.40
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  firebase_core_platform_interface: ^5.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseRemoteConfigWeb
        fileName: firebase_remote_config_web.dart
