name: firebase_core_web
description: The web implementation of firebase_core
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_core/firebase_core_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_core/firebase_core_web
version: 2.17.4

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  firebase_core_platform_interface: ^5.2.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.8.0
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseCoreWeb
        fileName: firebase_core_web.dart
