name: firebase_vertexai
description: "Firebase Vertex AI SDK."
version: 0.2.2+3
homepage: https://firebase.google.com/docs/vertex-ai/get-started?platform=flutter
topics:
  - firebase
  - vertexai
  - gemini
  - generative-ai

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  firebase_app_check: ^0.3.0+4
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_core_platform_interface: ^5.2.0
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3
