name: cloud_functions_web
description: The web implementation of cloud_functions
homepage: https://github.com/firebase/flutterfire/tree/main/packages/cloud_functions/cloud_functions_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/cloud_functions/cloud_functions_web

version: 4.9.11

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  cloud_functions_platform_interface: ^5.5.33
  firebase_core: ^3.3.0
  firebase_core_web: ^2.17.4
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  firebase_core_platform_interface: ^5.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFunctionsWeb
        fileName: cloud_functions_web.dart
