name: firebase_app_installations_web
description: The web implementation of firebase_app_installations.
version: 0.1.5+12
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_app_installations/firebase_app_installations_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_app_installations/firebase_app_installations_web

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.40
  firebase_app_installations_platform_interface: ^0.1.4+40
  firebase_core: ^3.3.0
  firebase_core_web: ^2.17.4
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  firebase_core_platform_interface: ^5.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppInstallationsWeb
        fileName: firebase_app_installations_web.dart
