name: cloud_firestore_web
description: The web implementation of cloud_firestore
homepage: https://github.com/firebase/flutterfire/tree/main/packages/cloud_firestore/cloud_firestore_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/cloud_firestore/cloud_firestore_web

version: 4.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.40
  cloud_firestore_platform_interface: ^6.3.0
  collection: ^1.0.0
  firebase_core: ^3.3.0
  firebase_core_web: ^2.17.4
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  firebase_core_platform_interface: ^5.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFirestoreWeb
        fileName: cloud_firestore_web.dart
